# vim:ft=kitty
## Theme collection "paradise". nvim counterpart: paradise
## (see COLORS.lua registry). No canonical standalone kitty port exists;
## colors hand-extracted from the full kitty.conf in the canon repo
## (cfg/kitty/kitty.conf), fonts/padding stripped.
## name: Paradise
## author: Manas140
## license: MIT
## upstream: https://github.com/paradise-theme/paradise/blob/main/cfg/kitty/kitty.conf
## blurb: Muted low-contrast pastel palette from the r/unixporn rice scene

foreground #E8E3E3
background #151515
url_color #E8E3E3

# black
color0 #151515
color8 #424242

# red
color1 #B66467
color9 #B66467

# green
color2 #8C977D
color10 #8C977D

# yellow
color3 #D9BC8C
color11 #D9BC8C

# blue
color4 #8DA3B9
color12 #8DA3B9

# magenta
color5 #A988B0
color13 #A988B0

# cyan
color6 #8AA6A2
color14 #8AA6A2

# white
color7 #E8E3E3
color15 #E8E3E3
